### ISSUE TITLE
Farming usage

### ISSUE THREAD

**Issue by MaxLeggieri** [pactfi/pact-js-sdk#27]
Dear all, i'm trying to fetch the available farms. It is not clear for me where to pick the appId of the farm. Is there something i'm missing? Is those ids fixed and can't be fetched?

Thanks so much
Max

**Comment by MaxLeggieri** [comment]
Any luck on this?

Thanks
Max

**Comment by tulustul** [comment]
The farms are not discoverable on-chain. You have to fetch the ids using the API.
https://api.pact.fi/api/farms/all
